Logger:
  Level: 0

HttpServer:
  Port: 8080
  ReadTimeout: 10s
  ReadHeaderTimeout: 500ms
  WriteTimeout: 10s
  IdleTimeout: 1s
  MaxHeaderBytes: 500
  ShutdownTimeout: 5s

Reservations:
  NotificationThreshold: 3
  PriceCoefficients:
    - Start: "2023-12-29"
      End: "2024-01-07"
      Rate: 1.2
    - Start: "2024-05-01"
      End: "2024-05-10"
      Rate: 1.3

AppCron:
  UpdateReservationsStatuses:
    Spec:
      - "30 * * * * *"
  GetForReminder:
    Spec:
      - "0 0 12 * * *"